
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class annualfunction extends javax.swing.JFrame {

    /**
     * Creates new form annualfunction
     */
    public annualfunction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        tf6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("ANNUAL FUNCTION REGISTRATION ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 134, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Candidate Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rb1.setText("JUNIOR (Class I - V )");
        getContentPane().add(rb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        rb2.setText("SENIOR ( Class VI - XII ) ");
        getContentPane().add(rb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Participation fees");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));
        getContentPane().add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 134, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Costume Charges ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        getContentPane().add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 134, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Makeup Charges");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        getContentPane().add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 134, -1));

        cb1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cb1.setText("Costume");
        getContentPane().add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        cb2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cb2.setText("Makeup");
        getContentPane().add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        jButton1.setText("CALCULATE TOTAL AMOUNT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel7.setBackground(java.awt.Color.pink);
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Total Amount");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 120, -1));

        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));
        getContentPane().add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 134, -1));

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/annualfunctionimage.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String nm = tf1.getText();
double pf = 0, cc = 0, mc = 0, t = 0;
if (rb1.isSelected() && cb1.isSelected() && cb2.isSelected())
{
    pf = pf + 1200;
    tf3.setText(""+pf);
    cc = cc + 800;
    tf4.setText(""+cc);
    mc = mc + 500;
    tf5.setText(""+mc);
    t = pf + cc + mc;
    tf6.setText(""+t);
}
else if (rb1.isSelected() && cb1.isSelected())
{
    pf = pf + 1200;
    tf3.setText(""+pf);
    cc = cc + 800;
    tf4.setText(""+cc);
    tf5.setText("0");
    t = pf + cc;
    tf6.setText(""+t);
  JOptionPane.showMessageDialog(null, "Make up should be done by the student as per the instructions. ");
}
else if (rb1.isSelected() && cb2.isSelected())
{
    pf = pf + 1200;
    tf3.setText(""+pf);
    mc = mc + 500;
    tf5.setText(""+mc);
    t = pf + mc;
    tf6.setText(""+t);
    tf4.setText("0");
  JOptionPane.showMessageDialog(null, "Costume should be arranged by the student as per the instruction. ");
}
else if (rb1.isSelected()) 
{
 pf = pf + 1200;
    tf3.setText(""+pf);
    tf4.setText("0");
    tf5.setText("0");
    t =t +pf;
    tf6.setText(""+t);
   JOptionPane.showMessageDialog(null,"Makeup and Costume should be arranged by the student as per the instruction." );
}
if (rb2.isSelected() && cb1.isSelected() && cb2.isSelected())
{
    pf = pf + 1800;
    tf3.setText(""+pf);
    cc = cc + 1000;
    tf4.setText(""+cc);
    mc = mc + 800;
    tf5.setText(""+mc);
    t = pf + cc + mc;
    tf6.setText(""+t);
}
else if (rb2.isSelected() && cb1.isSelected())
{
    pf = pf + 1800;
    tf3.setText(""+pf);
    cc = cc + 1000;
    tf4.setText(""+cc);
    tf5.setText("0");
    t = pf + cc;
    tf6.setText(""+t);
  JOptionPane.showMessageDialog(null, "Make up should be done by the student as per the instructions. ");
}
else if (rb2.isSelected() && cb2.isSelected())
{
    pf = pf + 1800;
    tf3.setText(""+pf);
    mc = mc + 800;
    tf5.setText(""+mc);
    tf4.setText("0");
    t = pf + mc;
    tf6.setText(""+t);
  JOptionPane.showMessageDialog(null, "Costume should be arranged by the student as per the instruction. ");
}
else if (rb2.isSelected()) 
{
 pf = pf + 1800;
    tf3.setText(""+pf);
    tf4.setText("0");
    tf5.setText("0");
    t =t +pf;
    tf6.setText(""+t);
   JOptionPane.showMessageDialog(null,"Makeup and Costume should be arranged by the student as per the instruction." );
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
tf1.setText("");
tf3.setText("");
tf4.setText("");
tf5.setText("");
tf6.setText("");
buttonGroup1.clearSelection();
cb1.setSelected(false);
cb2.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();
new homepage().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(annualfunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(annualfunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(annualfunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(annualfunction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new annualfunction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    // End of variables declaration//GEN-END:variables
}
