
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class schoolevents extends javax.swing.JFrame {

    /**
     * Creates new form schoolevents
     */
    public schoolevents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("SCHOOL CALANDER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 220, 31));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 13)); // NOI18N
        jLabel2.setText(" ACADMIC SESSION 2018-19");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 263, 40));

        jButton1.setText("JUNE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 130, -1, -1));

        jButton2.setText("JULY");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 130, -1, -1));

        jButton3.setText("JULY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 130, -1, -1));

        jButton4.setText("AUGUST");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 130, -1, -1));

        jButton5.setText("SEPTEMBER");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, -1, -1));

        jButton6.setText("OCTOBER");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 200, -1, -1));

        jButton7.setText("NOVEMBER");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 200, -1, -1));

        jButton8.setText("DECEMBER");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 200, -1, -1));

        jButton9.setText("JANUARY ");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, -1));

        jButton10.setText("FEBURARY");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 270, -1, -1));

        jButton11.setText("MARCH");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 270, -1, -1));

        jButton12.setText("BEGINNING OF NEW SESSION");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 333, -1, -1));

        jButton13.setText("ANNUAL HOLIDAY");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 333, -1, -1));

        jButton14.setText("BACK");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 406, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schooleventsimage.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
JOptionPane.showMessageDialog(null, "JUNE   \n"
        + "4th (Mon.)          School reopens for class IX - XII  \n"
        + " 6th (Wed.)         School reopens for class VI - VIII \n"
        + " 10th (Fri.)          School reopens for class Nur - V \n "
        + "12th (Mon.)        Allotment of Houses for new students of classes I - XII \n "
        + "26th(Fri.)            Inter-house Football matches (BOYS IX - XII) \n"
        + " 27th(Sat.)           Inter-house Football matches (GIRLS IX - XII) ");       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
JOptionPane.showMessageDialog(null,"JANUARY \n "
        + "1st(Fri.)              New Year Holiday  \n "
        + "2nd(sat.)           Drawing Competition for classes I - III \n "
        + "4th(Mon.)           Inter-house Debate Competition for VI - IX & XI \n "
        + "8th - 20th           II Term Examination for classes I - VIII \n (Fri. - Wed.)  \n "
        + "4th - 18th            II Pre Board Examination for classes X & XII \n(Mon. - Mon.) \n "
        + "16th(Sat.)           Extempore for classes IX & XI \n 23rd(sat.)           Picnic for classes VI - XII \n "
        + "26th(Tue.)          Republic Day Celebrations form 9:00 a.m. to 12:00 noon \n"
        + "                              (Attendence is Compulsory) \n "
        + "28th(Thu.)          Farewell for class XII \n "
        + "30th(Sat.)           Karate Competition for classes II - VIII ");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
JOptionPane.showMessageDialog(null,"DECEMBER \n "
        + "2nd(Tue.)            Volleyball Matches for classes IV & V \n "
        + "5th(Sat.)             Sports Day for classes Nur. - XII \n "
        + "7th - 9th               I Pre Board for classes X & XII \n(Mon. - Sat.)  \n "
        + "11th(Fri.)              Inter-house Singing Competition (English) for classes I - IX & XI \n "
        + "19th(Sat.)             Workshop for classes IX & XI \n "
        + "23rd(Wed.)           Christmas Celebration \n "
        + "24th - 27th            Christmas Holiays \n (Thu. - Sun.) \n "
        + "28th(Mon.)            Career Counseling for class X (Attendence compulsory ) \n "
        + "30th(Wed.)            Parent-Teacher Meeting for class XII \n "
        + "31st(Thu.)             New Year Holiday  ");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
JOptionPane.showMessageDialog(null," JULY\n "
        + "6th (Thu.)           Eye checkup session (I - V) \n "
        + "10th (Fri.)            Inter-house Basketball matches (BOYS   IX - XII) \n "
        + "11th (Sat.)           Inter-house Basketball matches (GIRLS   IX - XII) \n"
        + "18th (Tue.)           Inter-house Quiz Competition ( I - XII ) \n  "
        + "24th - 29th         Class Tests ( I - XII ) \n"
        + " (Mon.- sat.) \n Educational Trips for classes IX - XII \n "
        + "will be organized during the month of July ");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
JOptionPane.showMessageDialog(null,"SEPTEMBER \n "
        + "3rd (Wed.)       Janmashtami - Holiday \n "
        + "5th (Fri.)           Teachers  Day Celebration ( Nur.- XII) \n "
        + "9th - 23rd          I Term Examination ( I - XII ) \n (Fri. - Wed.) \n "
        + "25th (Fri.)          Inter-house vollyball matches (BOYS IX - XII) \n "
        + "26th (sat.)         Inter-house vollyball matches (GIRLS IX - XII) \n "
        + "28th (Mon.)       Anant Chaturthi - Holiday ");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
JOptionPane.showMessageDialog(null,"AUGUST \n"
        + "1st (Sat.)            Dental checkup sesssion (Nur. - K.G.II) \n "
        + "3rd (Mon.)          Yoga Competition (I - V) \n "
        + "6th (Wed.)          Parent- Teacher Meeting for classes I - VIII ( 9 : 00 a.m. - 11:00 a.m.)  \n "
        + "7th (Thu.)           Parent- Teacher Meeting for classes XI - XII ( 9 : 00 a.m. - 11:00 a.m.) \n "
        + "11th (Mon.)        Inter-house dramatics (English) for classes IX - XII \n "
        + "15th (Fri.)           Independence day Programme for classes I - XII ( 8:30 - 11:30 ) \n                              "
        + "(Attendence Compulsory) \n "
        + "25th - 28th         Green Hope programme (Nur. - XII) "
        + "\n (Tue. - Fri.) \n "
        + "29th (Sat.)          Raksha Bandhan  - Holiday");   // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
JOptionPane.showMessageDialog(null,"OCTOBER \n "
        + "2nd (Fri.)            Gandhi Jayanti - Holiday \n "
        + "5th (Mon.)          Inter-class Elocution Competition (IV - XII) \n "
        + "10th(Fri.)            Inter-house Cricket matches(BOYS IX - XII) \n "
        + "11th(Sat.)           Inter-house Cricket matches(GIRLS IX - XII) \n "
        + "17th(Sat.)           Dussehra Celebration (Nur. - XII) \n "
        + "19th - 22nd        Dussehra Holidays\n"
        + "(Mon.- Thu.) \n "
        + "23rd(Fri.)            Moharram - Holiday \n "
        + "18th - 25th          Excursion for classes IV - XII\n"
        + " (Sun. - Sun.)");       // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
JOptionPane.showMessageDialog(null,"NOVEMBER \n "
        + "3rd(Tue.)          Parent-Teacher Meeting for classes I - V \n "
        + "5th(Thu.)          Inter-house PPT Presentation (IX - XII) \n "
        + "9th - 13th         Diwali Holidays\n"
        + " (Mon. - Fri.) \n "
        + "14(Sat.)            Picnic for classes I - V \n "
        + "16th(Mon.)       Trekking for classes XI - XII \n "
        + "16th - 21st       Class Test for classes I - VIII, X & XII \n"
        + " (Mon. - Sat) \n"
        + "  Educational Trips for classes VI - VIII \n"
        + " will be conducted during the month of November");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
JOptionPane.showMessageDialog(null,"FEBURARY\n"
        + " 1st - 15th             Annual Examination For classes I - VIII \n"
        + " (Mon. - mon.) \n "
        + "4th (Thu.)            Cancer Day. To be marked by an awareness programme \n "
        + "20th(Sat.)            Extempore for classes VI - VIII \n "
        + "26th (Fri.)             Maha Shivratri - Holiday  ");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
JOptionPane.showMessageDialog(null,"MARCH \n "
        + "1st(Tue.)             Parent-Teacher Meeting for classes I - IV \n "
        + "5th(Sat.)              Orientation for the parents of classes X & XII \n "
        + "8th(Tue.)              Parent-Teacher Meeting for classes VI - VIII \n "
        + "12th(Sat.)             Science Exhibition for classes I - VIII \n "
        + "14(Mon.)               Holi - Holiday \n "
        + "18th(Fri.)               Rang Panchami - Holiday \n "
        + "21st(Mon.)            World Water Day. To be marked by an awareness programme \n "
        + "23rd(Wed.)            Last working day for classes Nur. - VIII  ");       // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
  JOptionPane.showMessageDialog(null,"BEGINNING OF NEW SESSION \n "
          + "1. Nursery - K.G.II          4th July(Mon.) 2019 \n "
          + "2. Classes I - VIII           15th June(Wed.) 2019 \n "
          + "3. Class IX                      2nd June(THu.) 2019 \n "
          + "4. Classes X & XII          2nd March(Wed.) 2019 \n "
          + "5. Class XI                      4th April(Mon.) 2019 ");      // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
   JOptionPane.showMessageDialog(null,"ANNUAL HOLIDAYS \n "
           + "1. Nursery - K.G.II                27th April 2019 - 3rd July 2019 \n "
           + "2. Classes I - VIII                 28th April 2019 - 14th June 2019 \n "
           + "3. Class IX                            28th April 2019 - 1st June 2019 \n "
           + "4. Classes X , XI & XII          1st May - 1st June ");
           // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
dispose();
new homepage().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(schoolevents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(schoolevents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(schoolevents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(schoolevents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new schoolevents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
